name: Promote Dialog to Production
on:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Promote Dialog to Production
        continue-on-error: true
        run: vercel promote dialogporto-ithacaxyz.vercel.app --token=${{ secrets.VERCEL_TOKEN }} --scope=ithacaxyz